### ISSUE TITLE
Add native desktop support for BTC and BCH

### ISSUE THREAD

**Issue by HostFat** [monicanagent/cypherpoker.js#49]
Are you even thinking about adding support for Bitcoin Cash? (as it has low fees)

**Comment by monicanagent** [comment]
Actually, you're the third person to mention this in the last 2 days :)

Yes, I'm planning on adding support for not only BCH but as many cryptocurrencies as possible. Before I committed to BCH, however, I needed to verify whether or not [the JSON-RPC API](https://www.bitcoincash.org/spec/JSON-RPC.html) was compatible with the [core (BTC)](https://bitcoin.org/en/developer-reference#rpc-quick-reference) one -- turns out it's nearly identical.

So I should be able to add native (desktop) support for BTC and BCH at the same. There are a few issues that precede this one but it's on the todo-very-soon list.

Tasks:

1. Add configuration options for bitcoind download/install URL and version matching
2. Create native downloader/installer for bitcoind
3. Add JSON-RPC client interface (possibly this: [https://www.npmjs.com/package/bitcoin-core](https://www.npmjs.com/package/bitcoin-core))
4. Update existing [account functionality](https://github.com/monicanagent/cypherpoker.js/blob/master/src/server/api/CP_Account.js) to use selected interface.

P.S. I changed the title of this issue to reflect the updated details.

**Comment by monicanagent** [comment]
Regarding the web version of CypherPoker.JS, I haven't yet been able to find any publicly accessible API service providers like BlockCypher that support posting of transactions without a custodial requirement. Most of them are read-only (e.g. https://bch.btc.com/api-doc), or require that you provide keys (https://www.bitgo.com/api/v2/#operation/v2.wallet.add)

If anyone knows of any public BCH API providers that support basic wallet (balance/send) functionality without requiring that I hand over private keys, please let me know.

With that in mind, BCH support for the web version likely won't be available until the desktop services (this issue), are implemented.

**Comment by HostFat** [comment]
Maybe you can find something useful here:
https://developer.bitcoin.com
https://rest.bitcoin.com
https://fountainhead.cash

**Comment by monicanagent** [comment]
Thanks. I'll check out those links..

**Comment by monicanagent** [comment]
Okay, it looks like adding BCH support to the web version should be do-able too. I've added this as issue #50.

**Comment by monicanagent** [comment]
Native handlers for BTC and BCH are implemented as of revision 197 (https://github.com/monicanagent/cypherpoker.js/commit/de4948a48ca1b1dc76f4376551f4f178a62f5987). This update includes raw transaction creation and signing which can be easily extended for use with remote APIs (see above in this issue description).

A "Bitcoin Cash" option still needs to be added to the user interface but the addition of remote APIs will be handled in issue #50.

**Comment by monicanagent** [comment]
Update completed in revision 199 (https://github.com/monicanagent/cypherpoker.js/commit/bbd75c311e428397f2ef8bab8b71b684ed3e2691).
